### ISSUE TITLE
Figure out why this piece of code works

### ISSUE THREAD

**Issue by nloomans** [MetisMontessoriLyceum/cyborg-rc2017#5]
[This piece of code](https://github.com/MetisMontessoriLyceum/cyborg-rc2017/blob/95040b9d3e7559856b06b4cc236d6286cc3fb6de/followLine.nxc#L53) should not work as the sensor switches between color and gray-scale mode constantly, guaranteeing `greenMrc` to be reset every other "tick".

However, this code appears to be working. It should be figured out why it works and if a bug is found in the process of doing so, fix it.

**Comment by bokke1010** [comment]
probably has something to do with the fact that these values only update every second frame, but can be read every frame, and as such aren't 'reset' at all

**Comment by nloomans** [comment]
The problem was that is checked if the difference was less then 20, or greater then 20. instead of -20 en 20.

This fix caused the code to break, like it should. That is fixed by only running the check when in green mode.
